feats: fbank80_stmn_16k.yaml
in_feats: 80
dropout_rate: 0
embed_dim: 10
cos_scale: 30
margin_warmup_epochs: 6.0
margin: 0.3
num_enc_blocks: 6
enc_d_model: 256
num_enc_heads: 4
enc_d_ff: 1024
enc_att_context: 6
min_chunk_length: 4
max_chunk_length: 4
iters_per_epoch: 6
epochs: 20
optim:
  amsgrad: true
  beta1: 0.9
  beta2: 0.95
  lr: 0.005
  opt_type: adam
  weight_decay: 1.0e-05
lrsched:
  decay_rate: 0.5
  decay_steps: 8000
  eps: 1.0e-08
  hold_steps: 16000
  lrsch_type: exp_lr
  min_lr: 1.0e-05
  update_lr_on_opt_step: true
  warmup_steps: 1000
