# Same as https://github.com/hyperion-ml/hyperion/blob/c4c9eee0acab1ba572843373245da12d00dfffaa/egs/voxceleb/v1/global_conf/config_transformer_lac6b6d512h8ff2048_arcs30m0.3_adam_lr0.005_amp.v1.sh
feats: fbank80_stmn_16k.yaml
in_feats: 80
dropout_rate: 0
embed_dim: 10
cos_scale: 30
margin_warmup_epochs: 20
margin: 0.3
num_enc_blocks: 6 
enc_d_model: 512
num_enc_heads: 8
enc_d_ff: 2048
enc_att_context: 6 # 250 ms
min_chunk_length: 4
max_chunk_length: 4
iters_per_epoch: 6
epochs: 20
optim:
  amsgrad: true
  beta1: 0.9
  beta2: 0.95
  lr: 0.005
  opt_type: adam
  weight_decay: 1.0e-05
lrsched:
  decay_rate: 0.5
  decay_steps: 12000
  eps: 1.0e-08
  hold_steps: 40000
  lrsch_type: exp_lr
  min_lr: 1.0e-05
  update_lr_on_opt_step: true
  warmup_steps: 1000

#--use-amp
#--enc-ff-type linear 
#--in-layer-type conv2d-sub
#--enc-att-type local-scaled-dot-prod-v1
